apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-conf
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    clients:
      - url: http://loki:3100/loki/api/v1/push
        backoff_config:
          min_period: 1s
          max_period: 30s
          max_retries: 20
        batchwait: 1s
        batchsize: 1048576
        timeout: 10s

    positions:
      filename: /run/promtail/positions.yaml

    scrape_configs:
    - job_name: kubernetes-pods
      static_configs:
      - targets:
          - localhost
        labels:
          job: kubernetes-pods
          __path__: /var/log/containers/*.log
      pipeline_stages:
      - cri: {}


    - job_name: kubernetes-system
      static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log

    - job_name: journal
      journal:
        max_age: 12h
        labels:
          job: systemd-journal
      relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'node'
      - source_labels: ['__journal_syslog_identifier']
        target_label: 'syslog_identifier'