apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.3
          ports:
            - containerPort: 3100
          args:
            - "-config.file=/etc/loki/loki.yaml"
          volumeMounts:
            # ConfigMap per il file di configurazione
            - name: config
              mountPath: /etc/loki
              readOnly: true
            # PersistentVolumeClaim per storage log
            - name: loki-storage
              mountPath: /loki
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
