apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: monitoring-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Michela877/Grafana.git
  ref:
    branch: fluxcd