apiVersion: v1
kind: Pod
metadata:
  name: test-logger
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "while true; do echo $(date); sleep 5; done"]
