apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: LoadBalancer    #commentare questi due se si vuole deployare con gateway ed url per grafana
  loadBalancerIP: <IL_TUO_IP_STATICO> # Sostituisci con il tuo IP pubblico commentare questi due se si vuole deployare con gateway ed url per grafana
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
