# testapp/complete-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: complete-app
  template:
    metadata:
      labels:
        app: complete-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: app
        image: busybox:latest
        command: ["/bin/sh"]
        args: 
        - -c
        - |
          # Installa curl e genera traffico
          apk add --no-cache curl
          while true; do
            # Genera log
            echo "$(date): INFO - Request processed successfully | method=GET path=/ status=200"
            echo "$(date): DEBUG - User action completed | user_id=123 action=login"
            echo "$(date): ERROR - Database connection failed | db_host=db.example.com attempt=3"
            
            # Genera trace (simulato nei log)
            echo "$(date): TRACE - span_id=abc123 trace_id=xyz456 service=complete-app operation=process_request duration=45ms"
            
            # Chiama se stesso per generare metriche HTTP
            curl -s http://complete-app:8080/metrics > /dev/null || true
            
            sleep 10
          done
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: complete-app
  namespace: default
spec:
  selector:
    app: complete-app
  ports:
  - port: 8080
    targetPort: 8080
