apiVersion: v1
kind: Secret
metadata:
  name: grafana-smtp-secret
  namespace: monitoring
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin
  GF_SMTP_ENABLED: "true"
  GF_SMTP_HOST: smtp.gmail.com:587
  GF_SMTP_USER: tuoindirizzo@gmail.com
  GF_SMTP_PASSWORD: lapassword
  GF_SMTP_FROM_ADDRESS: tuoindirizzo@gmail.com
  GF_SMTP_FROM_NAME: "Alerting Grafana"
  GF_SMTP_SKIP_VERIFY: "true" #true NON verifica il certificato (meno sicuro); false Verifica il certificato TLS (sicuro, produzione)
  GF_SMTP_STARTTLS_POLICY: Opportunistic
