apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-conf
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080

    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

    positions:
      filename: /run/promtail/positions.yaml

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod

        relabel_configs:
          # Crea l'etichetta __path__ che punta ai log reali
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_name, __meta_kubernetes_pod_container_name]
            target_label: __path__
            replacement: /var/log/pods/$1_$2_*/$3/*.log

          # Etichette base (namespace, pod, container)
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      hostNetwork: true
      serviceAccountName: promtail
      containers:
        - name: promtail
          image: grafana/promtail:2.9.3
          args:
            - --config.file=/etc/promtail/promtail.yaml
          ports:
            - containerPort: 9080
              name: http
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: run
              mountPath: /run/promtail
      volumes:
        - name: promtail-config
          configMap:
            name: promtail-conf
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: run
          hostPath:
            path: /run/promtail
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - services
    - pods
    verbs:
    - get
    - watch
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
subjects:
    - kind: ServiceAccount
      name: promtail
      namespace: monitoring
roleRef:
    kind: ClusterRole
    name: promtail
    apiGroup: rbac.authorization.k8s.io
