apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9080
    targetPort: http
  selector:
    app: promtail