apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: monitoring
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.3.1
          ports:
            - containerPort: 3200
            - containerPort: 4317
            - containerPort: 4318
          args:
            - "-config.file=/etc/tempo/tempo.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
            - name: tempo-storage
              mountPath: /tmp/tempo/traces   # qui vengono salvati i dati persistenti
      volumes:
        - name: config
          configMap:
            name: tempo-config
        - name: tempo-storage
          persistentVolumeClaim:
            claimName: tempo-pvc
