apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: monitoring
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: tempo
          image: grafana/tempo:2.3.1
          ports:
            - containerPort: 3200
            - containerPort: 9095
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 14250
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 14268
            - containerPort: 9411
            - containerPort: 55678
          args:
            - "-config.file=/etc/tempo/tempo.yaml"
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
            - name: tempo-storage
              mountPath: /var/tempo   # qui vengono salvati i dati persistenti
      volumes:
        - name: config
          configMap:
            name: tempo-config
        - name: tempo-storage
          persistentVolumeClaim:
            claimName: tempo-pvc
